### ISSUE TITLE
Kubernetes custom bitcoin.conf config

### ISSUE THREAD

**Issue by elderapo** [zquestz/docker-bitcoin#10]
What is the appropriate way to set custom settings in `bitcoin.conf` when using Kubernetes? For example how to set `dbcache=4000` or enable `txindex`?

Thanks for providing these awesome images btw!

**Comment by zquestz** [comment]
Here is a sample of how I do overrides, generally all from the command line args! Much easier than having to update the conf file.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: bitcoin
    version: 0.21.2
  name: bitcoin
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      service: bitcoin
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: bitcoin
    spec:
      containers:
      - args:
        - bitcoind
        - -externalip=35.208.255.10
        - -bantime=600
        - -whitelist=10.0.0.0/8
        - -txindex=1
        command:
        - /entrypoint.sh
        env:
        - name: BITCOIN_RPC_USER
          valueFrom:
            secretKeyRef:
              key: rpcuser
              name: bitcoin
        - name: BITCOIN_RPC_PASSWORD
          valueFrom:
            secretKeyRef:
              key: rpcpass
              name: bitcoin
        image: zquestz/bitcoin-cash-node:0.21.2
        imagePullPolicy: Always
        name: bitcoin
        resources:
          requests:
            memory: 5Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: bitcoin-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - gcePersistentDisk:
          fsType: ext4
          pdName: bitcoin-data
        name: bitcoin-data
```
